---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:"
  - "**.py"
exclude_paths:
- tests/
- darknet/

