sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  - postgresql
  - rabbitmq


before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get install -y ffmpeg

install: "pip install -r requirements.txt > /dev/null"

script:
  - python manage.py migrate
  - python run_ci_test.py
