sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  - postgresql
  - rabbitmq

before_script:
  - psql -c 'create database postgres;' -U postgres

install: "pip install -r requirements.txt"

script:
  - python manage.py migrate
