sudo: required

language: python

before_script: "sudo aptitude -y -q install ffmpeg libvpx-dev libvpx0 x264 libx264-85 libx264-dev"

python:
  - "2.7"

services:
  - docker
  - postgresql
  - rabbitmq

install: "pip install -r requirements.txt > /dev/null"

script:
  - python manage.py migrate
  - python run_ci_test.py
