sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  - postgresql
  - rabbitmq

virtualenv:
  system_site_packages: true

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get install -y ffmpeg
  - sudo apt-get install -y pkg-config python-dev python-opencv  libopencv-dev python-pip libav-tools   libjpeg-dev  libpng-dev  libtiff-dev  libjasper-dev  python-numpy  python-pycurl  python-opencv
  - sudo dpkg -L python-opencv

install: "pip install -r requirements.txt > /dev/null"

script:
  - python manage.py migrate
  - python run_ci_test.py
