sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  - postgresql
  - rabbitmq

addons:
  apt:
    packages:
    - ffmpeg


install: "pip install -r requirements.txt > /dev/null"

script:
  - python manage.py migrate
  - python run_ci_test.py
