sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  - postgresql
  - rabbitmq


before_install:
  - sudo apt-get update
  - sudo apt-get install libav-tools libavcodec-extra-54 -y

install: "pip install -r requirements.txt > /dev/null"

script:
  - python manage.py migrate
  - python run_ci_test.py
