services:
  db:
    container_name: dva-pg
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: postgres
    volumes:
    - dvapgdata:/var/lib/postgresql/data
    - nvidia_driver_367.57:/usr/local/nvidia:ro
  dva:
    build: .
    command: bash -c "git pull && fab start_server_container"
    container_name: dva-server
    depends_on:
    - db
    - rabbit
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: aub3dva:latest
    ports:
    - 8000:8000
    volumes:
    - dvadata:/root/DVA/dva/media
    - nvidia_driver_367.57:/usr/local/nvidia:ro
  rabbit:
    container_name: dva-rmq
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - RABBITMQ_DEFAULT_USER=dvauser
    - RABBITMQ_DEFAULT_PASS=localpass
    image: rabbitmq
    volumes:
    - dvarabbit:/var/lib/rabbitmq
    - nvidia_driver_367.57:/usr/local/nvidia:ro
version: '3'
volumes:
  dvadata: null
  dvapgdata: null
  dvarabbit: null
  nvidia_driver_367.57:
    external: true
