 version: '2'
 services:
   db:
     image: postgres
#   environment:
#     - POSTGRES_USER=dvauser
#     - POSTGRES_PASSWORD=localpass
   rabbit:
     image: rabbitmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
   web:
     build: .
     command: fab start_server_container
     ports:
       - "8000:8000"
     depends_on:
       - db
       - rabbit